import { Card } from "@/components/common/Card";
import {
	HomeIcon,
	ChartBarIcon,
	BeakerIcon,
	CloudIcon,
	BellAlertIcon,
	ClipboardDocumentCheckIcon,
	AcademicCapIcon,
	DocumentTextIcon,
	LightBulbIcon,
	ShieldCheckIcon,
} from "@heroicons/react/24/outline";

export const Help = () => {
	const sections = [
		{
			title: "Logging Data",
			icon: ClipboardDocumentCheckIcon,
			description:
				"The 'Quick Log' feature allows you to record Symptoms, Food, Activity, and Moodnow in seconds.",
			benefits: [
				"Standardized severity scales (1-10) for objective symptom tracking",
				"Meal-type categorization for better digestive pattern analysis",
				"Contextual logging ensures all variables are captured for the AI",
			],
		},
		{
			title: "Dashboard",
			icon: HomeIcon,
			description:
				"Your health command center. View a quick summary of your logs, active medications, and recent alerts at a glance.",
			benefits: [
				"Real-time overview of your current health status",
				"Quick stats to see if you're staying on track with logging",
				"Immediate visibility into critical alerts",
			],
		},
		{
			title: "Track & Analyze",
			icon: ChartBarIcon,
			description:
				"The core intelligence of PatternMD. This section combines statistical analysis with AI to find patterns you might miss.",
			benefits: [
				"Statistical Correlations: See how factors like weather or mood impact your symptoms",
				"AI Health Insights: Personalized analysis generated by our medical-grade AI model",
				"Trigger Discovery: Automatically identify specific foods or activities that precede symptom spikes",
			],
		},
		{
			title: "Medications",
			icon: BeakerIcon,
			description:
				"Manage your prescriptions and track adherence. Set up schedules and log when you take your doses.",
			benefits: [
				"Never miss a dose with integrated reminder alerts",
				"Track 'as-needed' vs scheduled medication effectiveness",
				"Maintain a clear history for your healthcare provider",
			],
		},
		{
			title: "Environment",
			icon: CloudIcon,
			description:
				"Automatically tracks external factors that could affect your health, such as temperature, humidity, and air quality.",
			benefits: [
				"Discover weather sensitivities (e.g., barometric pressure or high humidity triggers)",
				"Automatic logging based on your location reduces manual effort",
				"Correlate air quality with respiratory or inflammatory symptoms",
			],
		},
		{
			title: "Alerts & Reminders",
			icon: BellAlertIcon,
			description: "Stay informed about your health schedule and critical pattern discoveries.",
			benefits: [
				"Timely notifications for medication and logging",
				"Immediate warnings when high-severity patterns are detected",
				"System-wide updates on analysis status",
			],
		},
		{
			title: "Research",
			icon: AcademicCapIcon,
			description:
				"Access a curated library of medical research and case studies related to chronic conditions and symptom management.",
			benefits: [
				"Stay informed with the latest evidence-based health findings",
				"Learn about emerging treatments and management strategies",
				"Understand the science behind common symptom triggers",
			],
		},
		{
			title: "Reports",
			icon: DocumentTextIcon,
			description:
				"Generate comprehensive health summaries and PDF reports designed to be shared with your healthcare providers.",
			benefits: [
				"Improve communication with your doctor using objective data",
				"Export long-term trends to help with diagnosis and treatment adjustments",
				"Reduce appointment time spent recalling symptom history",
			],
		},
	];

	return (
		<div className="space-y-8 max-w-5xl mx-auto">
			<div className="text-center">
				<h1 className="text-3xl font-bold text-gray-900">How PatternMD Works</h1>
				<p className="text-gray-600 mt-2 text-lg">
					Learn how to use each feature to gain deep insights into your health.
				</p>
			</div>

			<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
				{sections.map((section) => (
					<Card key={section.title} className="hover:shadow-md transition-shadow">
						<div className="flex items-start space-x-4">
							<div className="p-2 bg-primary-100 rounded-lg">
								<section.icon className="w-6 h-6 text-primary-600" />
							</div>
							<div className="flex-1">
								<h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
								<p className="text-gray-600 mt-2 leading-relaxed">{section.description}</p>
								<div className="mt-4 space-y-2">
									<h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider flex items-center">
										<LightBulbIcon className="w-4 h-4 mr-1" />
										Key Benefits
									</h3>
									<ul className="space-y-1">
										{section.benefits.map((benefit, idx) => (
											<li key={idx} className="text-sm text-gray-700 flex items-start">
												<span className="text-primary-500 mr-2">•</span>
												{benefit}
											</li>
										))}
									</ul>
								</div>
							</div>
						</div>
					</Card>
				))}
			</div>

			<Card className="bg-primary-50 border-primary-100">
				<div className="flex items-center space-x-4">
					<ShieldCheckIcon className="w-10 h-10 text-primary-600 shrink-0" />
					<div>
						<h2 className="text-lg font-bold text-primary-900">Your Privacy & Data</h2>
						<p className="text-primary-800">
							All health data is encrypted and used solely for your personal insights. Our AI processing
							is designed to find correlations without compromising your anonymity.
						</p>
					</div>
				</div>
			</Card>
		</div>
	);
};
