"""add enhanced environmental metrics

Revision ID: 162edbf5d057
Revises: 09e3322d0437
Create Date: 2026-01-06 14:33:40.526237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162edbf5d057'
down_revision = '09e3322d0437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feels_like', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pm2_5', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pm10', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.drop_column('pm10')
        batch_op.drop_column('pm2_5')
        batch_op.drop_column('visibility')
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('feels_like')

    # ### end Alembic commands ###
