"""add clouds to environment logs

Revision ID: 25f4349e25ef
Revises: f0d34e38b3a1
Create Date: 2026-01-06 14:51:22.944724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f4349e25ef'
down_revision = 'f0d34e38b3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clouds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.drop_column('clouds')

    # ### end Alembic commands ###
