"""Initial migration

Revision ID: 9bdb0807549b
Revises: 
Create Date: 2026-01-03 23:55:27.229984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdb0807549b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('environment_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('pollen_count', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_logs_user_id'), ['user_id'], unique=False)

    op.create_table('food_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('portion_size', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_user_id'), ['user_id'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_user_id'), ['user_id'], unique=False)

    op.create_table('mood_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mood_rating', sa.Integer(), nullable=False),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_logs_user_id'), ['user_id'], unique=False)

    op.create_table('patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('symptom_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('body_location', sa.String(length=100), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_logs_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_pattern_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['related_pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('medication_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_logs_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_medication_logs_medication_id'))

    op.drop_table('medication_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))

    op.drop_table('alerts')
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_logs_timestamp'))

    op.drop_table('symptom_logs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))

    op.drop_table('reports')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_user_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_logs_timestamp'))

    op.drop_table('mood_logs')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_user_id'))

    op.drop_table('medications')
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_logs_timestamp'))

    op.drop_table('food_logs')
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_environment_logs_timestamp'))

    op.drop_table('environment_logs')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_timestamp'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
