"""add uv_index to environment logs

Revision ID: f0d34e38b3a1
Revises: 162edbf5d057
Create Date: 2026-01-06 14:41:06.564552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d34e38b3a1'
down_revision = '162edbf5d057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uv_index', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_logs', schema=None) as batch_op:
        batch_op.drop_column('uv_index')

    # ### end Alembic commands ###
